Inclusion of backbone models for general purpose
pyg-team/pytorch_geometric pull request #2867
Opened 2021-07-15 15:32 UTC by PabloAMC

Code adapted mostly from benchmark folder to create models not so specific as the present ones

2021-07-15 16:57 UTC, rusty1s commented
Thanks a lot. Before this becomes too complicated to review, can we first merge some of the basic GNNs without any fancy pooling?

2021-07-21 21:57 UTC, PabloAMC commented
I have added models for GINE, GATv2, ASAPool, SAGPool, Graclus and EdgePool, including tests

2021-08-05 16:45 UTC, rusty1s requested changes

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_gnn.py
> +class GINE(BasicGNN):
We can also inherit from `GIN`, which makes the `GIN.MLP` call a little bit more cleaner.

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_gnn.py
> +    :class:`~torch_geometric.nn.GINConv` operator for message passing.
GINE

2021-08-05 16:45 UTC, rusty1s commented on test/nn/models/test_basic_gnn.py
> +def test_gine(dropout, act, norm, jk):
The `GINE` module expects `edge_attr` as input to the `forward` function.

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_gnn.py
> +            :class:`torch_geometric.nn.conv.GINConv`.
GINE

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_gnn.py
> +    :class:`~torch_geometric.nn.GATConv` operator for message passing.
GATv2

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_gnn.py
> +        **kwargs (optional): Additional arguments of
GATv2

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_pools.py
> +class BasicPoolGNN(torch.nn.Module):
Is it possible to inherit from `BasicGNN`?

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_pools.py
> +                 glob_pool: str = 'mean'):
`global_pool`?

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_pools.py
> +                pool = self.pools[i // 2]
I think we should create a function `self.pool(layer, x, edge_index, batch, *kwargs)` that takes care of pooling, and that one needs to override. I think not all pooling ops are perfectly aligned to this interface yet.

2021-08-05 16:45 UTC, rusty1s commented on torch_geometric/nn/models/basic_pools.py
> +        self.convs.append(GraphConv(in_channels, hidden_channels, **kwargs))
Can we allow  different GNN ops as well?

2021-12-30 13:49 UTC, PabloAMC commented
I'm closing this PR because the basic models were already open.

2021-12-30 13:49 UTC, closed without merging