build: support `skip-changelog` in changelog enforcer
pyg-team/pytorch_geometric pull request #5377
Opened 2022-09-07 19:21 UTC by mananshah99

2022-09-07 20:47 UTC, rusty1s commented
Why do we need this?

2022-09-07 20:48 UTC, mananshah99 commented
This allows folks to add the skip-changelog tag after a PR is created, upon which the action will automatically re-run.

2022-09-08 04:55 UTC, rusty1s requested changes
Got it. Thanks for clarifying!

2022-09-08 04:55 UTC, rusty1s approved these changes

2022-09-08 04:59 UTC, merged