Improve multi-node multi-gpu tutorial
pyg-team/pytorch_geometric pull request #8353
Opened 2023-11-09 14:18 UTC by flxmr

So, in response to my remarks in #8071 I now prepared this PR for updating the multi-node documentation (sadly no student contrib, they can prep multi-gpu metrics).

Reasoning:
- if pyg has a tutorial on DDP it's for people who essentially grow within pyg to this usecase. This should be reflected in telling them more about this and be clear on what is done (like `torch.multiprocessing` injecting the rank. it seems very random otherwise).
- in the same vein, the multi-node tutorial should evolve from the single-node one imho. 
- embedding the pyxis-container as the only way to do things is good for Nvidia, but bad for people who arrive on a system without that.

Things I skipped:
- setting up the worker-count. I would say people should just figure this out on their own. the `os.sched_getaffinity` is cool, but this is a very general problem too and I essentially do it manually now.
- anything GRES-related. I doubt that anyone growing into this and installing slurm on their computers will not grok this. Every multi-user, public research system has GRES I'd say (and everyone has their internal docs).

2023-11-13 14:56 UTC, akihironitta commented on docs/source/tutorial/multi_node_multi_gpu_vanilla.rst
```suggestion
Multi-Node-Multi-GPU Training using SLURM
=========================================

```

2023-11-13 14:56 UTC, akihironitta commented on docs/source/tutorial/multi_node_multi_gpu_vanilla.rst
> +    export MASTER_ADDR=$master_addr
```suggestion
    export MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
```

2023-11-13 14:56 UTC, akihironitta commented on docs/source/tutorial/multi_node_multi_gpu_vanilla.rst
> +    $ sbatch distributed_sampling_multinode.sbatch
nit: Should we remove `$` for consistency?
```suggestion
    sbatch distributed_sampling_multinode.sbatch
```

2023-11-13 14:56 UTC, akihironitta commented on docs/source/tutorial/multi_node_multi_gpu_vanilla.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
Using a cluster configured with pyxis-containers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-11-13 14:56 UTC, akihironitta commented on docs/source/tutorial/multi_node_multi_gpu_vanilla.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
Modifying the training script
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-11-13 16:27 UTC, akihironitta approved these changes
I'm not a slurm expert, but LGTM. Just pushed a few commits, but feel free to revert them if you think otherwise.

2023-11-13 23:26 UTC, flxmr commented
I didn't find how to make the `srun`-only example work with the containers. The current example which I just copied doesn't work: there is no environment variables in the pytorch-only NGC-container and I wonder how those would be injected anyway. Also the mounting doesn't make sense. So now it is sbatch only, but verified to work on our local HPC (which also has a tutorial on modifying the enroot-container).

In addition I noticed by trying this, that having multiple processes download data and then trying to unzip it is not working well (it worked previously, because the data was downloaded already). Fixed that too.

2023-11-14 00:26 UTC, puririshi98 approved these changes
LGTM, thanks for the improvements :)

2023-11-14 00:29 UTC, puririshi98 requested changes
Although it looks good to me we should definitely make sure containers work as my original PR was tested working on a pyxis enabled nvidia cluster using our NVIDIA early access PyG container.

2023-11-14 08:39 UTC, flxmr commented
So, I checked again and it seems `pyxis/enroot` is indeed injecting the `LOCAL_RANK` and `RANK` into the container: https://github.com/NVIDIA/enroot/blob/master/conf/hooks/extra/50-slurm-pytorch.sh#L32-L37

it seems to be quite a mess though (user→slurm→pyxis→enroot): https://github.com/NVIDIA/pyxis/issues/46#issuecomment-840283874

As for the `MASTER_ADDRESS` - maybe this is site-configuration specific (I could imagine running a [prolog](https://slurm.schedmd.com/prolog_epilog.html)), [they have it](http://projects.dfki.uni-kl.de/km-publications/web/ML/core/hpc-doc/docs/slurm-cluster/multi-gpu-distributed-jobs/) our HPC centers DGX don't have it!

2023-11-14 18:32 UTC, puririshi98 commented
@flxmr  I will investigate and get back to you as soon as I can

2023-11-14 22:39 UTC, puririshi98 commented
@flxmr i asked around internally with our enroot team 
```
Pytorch is supported through this enroot hook: https://github.com/NVIDIA/enroot/blob/master/conf/hooks/extra/50-slurm-pytorch.sh
It is shipped by default and just need to be enabled by the administrator
```
does this help? I can follow back up if not.

2023-11-16 09:09 UTC, flxmr commented
So, hope this works now for everyone. I added a link to this issue because I suppose if our HPC didn't like the hook, others might not like it too.

2023-11-16 18:25 UTC, puririshi98 approved these changes
LGTM now, thanks @flxmr for this great PR

2023-11-16 18:27 UTC, merged