Add note on network interface in distributed examples README
pyg-team/pytorch_geometric pull request #8928
Opened 2024-02-16 18:08 UTC by Kh4L

2024-02-16 18:21 UTC, puririshi98 requested changes

2024-02-16 18:21 UTC, puririshi98 commented on examples/distributed/pyg/README.md
> +In some configurations, the network interface used for multi-node communication may be different not the default one.
```suggestion
In some configurations, the network interface used for multi-node communication may be different than the default one.
```

2024-02-16 18:21 UTC, puririshi98 commented on examples/distributed/pyg/README.md
> +Assuming that `$MASTER_ADDR` is set the the IP of `node#0`.
```suggestion
Assuming that `$MASTER_ADDR` is set to the IP of `node#0`.
```

2024-02-17 14:11 UTC, rusty1s approved these changes

2024-02-17 14:11 UTC, merged