[Example] Add WholeGraph to accelerate PyG dataloaders with GPUs
pyg-team/pytorch_geometric pull request #9714
Opened 2024-10-17 23:04 UTC by chang-l

This PR demonstrates how to integrate the [NVIDIA WholeGraph](https://github.com/rapidsai/wholegraph) into PyG’s graph and feature store base classes, providing a modular and PyG-like way to extend PyG's dataloader for better GPU utilization. Let WholeGraph handle the optimization of data access on NVIDIA hardware and manage graph and feature storage, with potential sharding across distributed disk, RAM or device memory.

Compared to existing examples, there are three key differences:

The WholeGraph library does not provide a dataloader but host underlying distributed graph and feature storage with associated efficient primitive operations (e.g., GPU-accelerated fast embedding retrieval and graph sampling).

It is efficient, minimizing CPU interruptions, and can be built into PyG's feature store and graph store (compatible with existing PyG native dataloaders). Please see `feature_store.py` and `graph_store.py` implementation.

There is no distinction between single-GPU, multi-GPU, and multi-node multi-GPU training with this new feature store or graph store. Users do not need to partition the graph or hand-craft third-party launch scripts. Everything falls under the traditional PyTorch DDP workflow,  The example (`papers100m_dist_wholegraph_nc.py` or `benchmark_data.py`) shows how to achieve this from any existing PyG DDP example.

By running benchmark script (`benchmark_data.py`), we observed **2X, 5X and 9X** speedup on **single** GPU with NVIDIA **T4, A100, and H100** GPU, compared to native PyG NeighborLoader. Running with 4 GPUs, the speedups increase to **6.4X, 15X and 35X**, respectively (numbers may vary depending on actual CPU used for baseline run).

Meanwhile, I’d like to propose officially integrating WholeGraph, as an option, to back `data.FeatureStore`/`HeteroData.FeatureStore` first; and to support the WholeMemory type as a new option in `index_select` function; https://github.com/pyg-team/pytorch_geometric/blob/7f844d72d307ab9a105ba6494824cb0205ccbeac/torch_geometric/loader/utils.py#L57, making it accessible to more users.

2024-10-22 16:53 UTC, puririshi98 requested changes
Overall looks good to me. @rusty1s I wonder if you think it would be a better fit to have these helper files directly integrated into torch_geometric.distributed.wholegraph or something like that.

also @chang-l please remove the stale examples from examples/multi_gpu/

these:
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/data_parallel.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_batching.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling_multinode.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling_multinode.sbatch
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/mag240m_graphsage.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/papers100m_gcn.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/papers100m_gcn_multinode.py


for taobao and pcqm4m examples in the folder, i think it would be best to add a comment to the top mentioning mp.spawn is deprecated and to point to your new examples.

lastly. please add similar deprecation comment and pointer to new examples for these 2:
https://github.com/pyg-team/pytorch_geometric/blob/master/docs/source/tutorial/multi_gpu_vanilla.rst
https://github.com/pyg-team/pytorch_geometric/blob/master/docs/source/tutorial/multi_node_multi_gpu_vanilla.rst

2024-10-22 16:58 UTC, alexbarghi-nv commented
> Overall looks good to me. @rusty1s I wonder if you think it would be a better fit to have these helper files directly integrated into torch_geometric.distributed.wholegraph or something like that.
> 
> also @chang-l please remove the stale examples from examples/multi_gpu/
> 
> these: https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/data_parallel.py https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_batching.py https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling_multinode.py https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling_multinode.sbatch https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/mag240m_graphsage.py https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/papers100m_gcn.py https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/papers100m_gcn_multinode.py
> 
> for taobao and pcqm4m examples in the folder, i think it would be best to add a comment to the top mentioning mp.spawn is deprecated and to point to your new examples. please also update the readme of that folder accordingly.
> 
> lastly. please add similar deprecation comment and pointer to new examples for these 2: https://github.com/pyg-team/pytorch_geometric/blob/master/docs/source/tutorial/multi_gpu_vanilla.rst https://github.com/pyg-team/pytorch_geometric/blob/master/docs/source/tutorial/multi_node_multi_gpu_vanilla.rst

@puririshi98 can we hold off on for now?  We have having a meeting in a couple hours to discuss this PR and how we want to go about it.

2024-10-22 19:54 UTC, alexbarghi-nv commented
@puririshi98 @chang-l We can go ahead and instruct users to use `torchrun` and the example WG Graph/Feature stores.  At some point, we will replace the ones in the examples directory with official ones that are part of `cugraph`.  Our long-term strategy, I think, based on our discussion, is to have this take over feature storage in cuGraph.  The cuGraph loaders will remain for users that need them for extreme scale applications.  Then, for sampling, we will eventually replace the WholeGraph samplers with cuGraph ones once our C++ code can support custom partitioning schemes.

2024-10-22 20:18 UTC, chang-l commented
Okay, I guess, from our side, we can keep this PR as it is (as one of distributed example) for now and gradually merge it within cuGraph along the way while keeping the examples up to date. Sounds good? @alexbarghi-nv @puririshi98 @TristonC @BradReesWork

2024-10-22 20:20 UTC, alexbarghi-nv commented
@chang-l sounds good to me 👍

2024-10-22 20:38 UTC, chang-l commented
@puririshi98   Thank you Rishi for the suggestions. I will file another PR to update and reorg existing multiGPU/multi-node examples.

2024-11-01 23:49 UTC, chang-l commented on examples/distributed/NVIDIA-RAPIDS/cugraph/papers100m_gcn_cugraph_multinode.py
@alexbarghi-nv  do you mind add a README file under this directory later?

2024-11-06 22:28 UTC, chang-l commented
Per @puririshi98 suggestion, I updated the comment for most examples in [this folder](https://github.com/pyg-team/pytorch_geometric/tree/master/examples/multi_gpu). 
We will continuously work on improving our single-node, multi-GPU examples.

2024-11-12 15:53 UTC, alexbarghi-nv commented on examples/distributed/NVIDIA-RAPIDS/cugraph/papers100m_gcn_cugraph_multinode.py
# Distributed Training with cuGraph-PyG

**[RAPIDS cuGraph-PyG](https://github.com/rapidsai/cugraph-gnn)** is an extension for PyG that supports accelerated data loading and feature fetching.  It is powered by **[RAPIDS cuGraph](https://github.com/rapidsai/cugraph)**

cuGraph-PyG supports single-GPU, multi-GPU, and multi-node/multi-GPU training and sampling using native PyG APIs.

## Requirements
**PyTorch**: `>=2.3`
**TensorDict**:`>=0.1.2`
**cuGraph-PyG**:`>=24.08`
**WholeGraph**:`>=24.08`
**CUDA**:`>=11.8`
**NVIDIA GPU(s) with compute capability 7.0+**

For more documentation on how to install RAPIDS, see this [guide](https://docs.rapids.ai/install).

## How to Run
 To run, use sbatch
 (i.e. `sbatch -N2 -p <partition> -A <account> -J <job name>`)
 with the script shown below:

```
 head_node_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)

 (yes || true) | srun -l \
        --container-image <container image> \
        --container-mounts "$(pwd):/workspace","/raid:/raid" \
          torchrun \
          --nnodes 2 \
          --nproc-per-node 8 \
          --rdzv-backend c10d \
          --rdzv-id 62 \
          --rdzv-endpoint $head_node_addr:29505 \
          /workspace/papers100m_gcn_cugraph_multinode.py \
            --epochs 1 \
            --dataset ogbn-papers100M \
            --dataset_root /workspace/datasets \
            --tempdir_root /raid/scratch
```

2024-11-12 19:52 UTC, alexbarghi-nv approved these changes
👍

2024-11-19 11:04 UTC, Kh4L commented on examples/distributed/NVIDIA-RAPIDS/wholegraph/nv_distributed_graph/wholegraph.py
> +def sample_nodes_wmb_fn(wg_sampler, seeds, fanouts):
This function is not used in the code

2024-12-31 18:42 UTC, chang-l commented on examples/distributed/NVIDIA-RAPIDS/wholegraph/nv_distributed_graph/wholegraph.py
> +def sample_nodes_wmb_fn(wg_sampler, seeds, fanouts):
Thanks @Kh4L.

2025-01-22 17:08 UTC, puririshi98 commented
closing for @alexbarghi-nv to include in cugraph herself

2025-01-22 17:08 UTC, closed without merging