Large Graph Indexer WebQSP Refactor and GRetriever Documentation changes
pyg-team/pytorch_geometric pull request #9806
Opened 2024-11-25 20:04 UTC by zaristei

Successor to [9666](https://github.com/pyg-team/pytorch_geometric/pull/9666), this updates the documentation to show how to utilize GNN RAG and updates WebQSP to help serve as a toy example.

2024-12-11 21:44 UTC, puririshi98 commented
will merge this once zack joins full time and has bandwidth and compute to debug and ensure that merging his PR keeps test hit metric the same or higher (not lower as is now).

2025-03-05 18:02 UTC, puririshi98 requested changes

2025-03-05 18:02 UTC, puririshi98 commented on torch_geometric/datasets/web_qsp_dataset.py
> +        # TODO: @riship should this be done in the base class?
yes

2025-03-05 18:02 UTC, puririshi98 commented on torch_geometric/datasets/web_qsp_dataset.py
> +        # NOTE: Current behavior is to process the entire dataset, and only return the split specified by the user
if you call this dataset 3 times
```
WebQSP(split="train")
..
Webqsp(..
```
it just processes it once and then returns train on the first call, but the val and test ones just pull from the already processed data

2025-04-01 23:57 UTC, zaristei commented on torch_geometric/datasets/web_qsp_dataset.py
> +    h, r, t = triplet
Referring to this one creates a circular import, so I'm going to keep my copy in `web_qsp_dataset.py` for now.

2025-04-02 01:06 UTC, merged