Draft: TXT2KG` w/ `hotpot_qa.py` example for precision estimation
pyg-team/pytorch_geometric pull request #9846
Opened 2024-12-11 22:06 UTC by puririshi98

rebased https://github.com/pyg-team/pytorch_geometric/pull/9728

2024-12-11 22:07 UTC, puririshi98 commented
@Kh4L reviews welcome

2024-12-13 03:01 UTC, Kh4L requested changes
A few nitpicks, but LGTM!

2024-12-13 03:01 UTC, Kh4L commented on examples/llm/hotpot_qa.py
> +    parser.add_argument('--chunk_size', type=int, default=512)
Would be nice to have example-level descriptions for the less obvious args, like `chunk_size`

2024-12-15 15:43 UTC, Kh4L requested changes

2024-12-15 15:43 UTC, Kh4L commented on torch_geometric/nn/nlp/txt2kg.py
> +            assert NVIDIA_API_KEY != '', "Please pass NVIDIA_API_KEY or set local_small_lm flag to True"
```suggestion
            assert NVIDIA_API_KEY != '', "Please pass NVIDIA_API_KEY or set local_lm flag to True"
```

2024-12-19 19:47 UTC, puririshi98 commented on torch_geometric/nn/nlp/txt2kg.py
> +    split_by_newline = triples_str.split("\n")
the prompt asks the LLM to seperate by newline and its generally good at this. the split below handles other cases

2024-12-28 16:38 UTC, akihironitta requested changes
Great work! 🚀 I may have missed some past PRs that were already merged, but I'm sharing my thoughts here anyway :)

I think we might want to make sure that anything goes under `torch_geometric/` is general enough, well documented, well tested so that it's reusable by users outside these example scripts. If these utils under `torch_geometric/` are not general enough, users might end up copying the code into their own scripts instead of directly relying on `torch_geometric/`.

If the intention is for these LLMs+GNNs additions to serve as reference implementations (that users can tweak as needed), it'd make more sense to include them as examples rather than integrating them into `torch_geometric/`.

2024-12-28 16:38 UTC, akihironitta commented on torch_geometric/nn/nlp/llm.py
> -    num_params (int): An integer representing how many parameters the
What's the unit of this arg? Can we document it?

2024-12-28 16:38 UTC, akihironitta commented on torch_geometric/nn/nlp/txt2kg.py
> +    """
It's not clear to me how to use this class. Can we document an example usage (and/or add a reference to the example)?

2025-01-06 18:08 UTC, puririshi98 commented on torch_geometric/nn/nlp/llm.py
> -    num_params (int): An integer representing how many parameters the
"An integer representing how many parameters the
        HuggingFace model has, in billions."
it mentions this is in billions.
Is there a different way you would like me to note this?

2025-01-07 01:21 UTC, puririshi98 commented
"I think we might want to make sure that anything goes under torch_geometric/ is general enough, well documented, well tested so that it's reusable by users outside these example scripts"

btw this is still a draft, i aim to have full docstrings etc and polish this up once its ready

2025-01-25 10:21 UTC, Kh4L commented on torch_geometric/nn/models/g_retriever.py
> +        mlp_out_channels = llm.word_embedding.embedding_dim
Move this to L76 for readability

2025-01-25 10:21 UTC, Kh4L commented on torch_geometric/nn/nlp/txt2kg.py
> +            self.model = LLM(LM_name, num_params=14).eval()
You can drop the num_params after #9938

2025-01-25 10:21 UTC, Kh4L commented on examples/llm/hotpot_qa.py
> +    for QA_pair in loader:
```suggestion
for QA_pair in tqdm(relevant_triples.keys(), disable=args.verbose):
```

2025-01-25 10:21 UTC, Kh4L commented on examples/llm/hotpot_qa.py
> +        num_relevant_out_of_retrieved = float(
You can do:
```
num_relevant_out_of_retrieved  = float(
                             sum(retrieved_triple in golden_triples 
                                 for retrieved_triple in retrieved_triples)
                             )
```

2025-01-27 02:16 UTC, puririshi98 commented on torch_geometric/nn/nlp/txt2kg.py
> +            self.model = LLM(LM_name, num_params=14).eval()
good catch

2025-01-29 21:45 UTC, puririshi98 commented
accidentally merged wrong pr into this closing, making new

2025-01-29 21:45 UTC, closed without merging